version: '3'
services:
  webtop-xfce4-alpine:
    build:
      dockerfile: xfce4.Dockerfile
      context: ../../src/alpine
    security_opt:
      - seccomp:unconfined # Need for most cases
    environment:
      - PGUID=$PGID
      - PUID=$PUID
      - TZ=Asia/Manila
    ports:
      - 8080:3000
    cap_add:
      - NET_ADMIN
    volumes:
      - ../data/xrdp:/etc/xrdp
      - $HOMEDIR:/config
      - /var/run/docker.sock:/var/run/docker.sock
      - ../data/tailscale-statedir:/var/lib/tailscale
    env_file:
      - ../../.env

# Not being used here
#volumes:
#  xrdp-config:
