version: '3'
services:
  webtop-xfce4-alpine:
    image: ghcr.io/ajhalili2006/webtop-alpine-xfce4:latest
    security_opt:
      - seccomp:unconfined # Required to fix the "failed to fdwalk operation not permitted" error on Docker side.
    environment:
      - PGUID=$PGID
      - PUID=$PUID
      - TZ=Asia/Manila
    ports:
      - 8080:3000
    cap_add:
      - NET_ADMIN # For Tailscale stuff
    volumes:
      - ../data/xrdp:/etc/xrdp
      - $HOMEDIR:/config
      - /var/run/docker.sock:/var/run/docker.sock
      - ../data/tailscale-statedir:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    env_file:
      - ../../.env

#volumes:
#  xrdp-config:
