name: Alpine Linux CI

on:
  push:
    branches:
      - main
    paths:
      - src/alpine/xfce4.Dockerfile
      - src/alpine/overlay/**
  workflow_dispatch:

env:
  # Registry namespaces, to avoid only-lowercase-supported errors
  GHCR_NAMESPACE: ajhalili2006
  RHQCR_NAMESPACE: ajhalili2006
  # Service account stuff for Quay.io
  RHQCR_BOT_ACCOUNT: ajhalili2006+gildedguy
  RHQCR_BOT_PASSWORD: ${{ secrets.RHQCR_SERVICE_ACCOUNT_API_KEY }}

  # GHCR
  GHCR_PAT: ${{ secrets.LTT_STORE_DOT_COM }}
  # may not work if forked in an org, use an bot account instead
  GHCR_USERNAME: ${{ github.repository_owner }}

  # Other stuff for Docker builds
  image_name: webtop-alpine-xfce4
  context: src/alpine
  dockerfile: xfce4.Dockerfile

jobs:
  build-xfce4:
    name: Build Xfce4 variant
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login with GHCR
        uses: docker/login-action@v1
        with:
          username: ${{ env.GHCR_USERNAME }}
          password: ${{ env.GHCR_PAT }}
          registry: ghcr.io
      - name: Login with RHQCR
        uses: docker/login-action@v1
        with:
          username: ${{ env.RHQCR_BOT_ACCOUNT }}
          password: ${{ env.RHQCR_BOT_PASSWORD }}
          registry: quay.io
      - name: Generate matadata
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            ghcr.io/${{ env.GHCR_NAMESPACE }}/${{ env.image_name }}
            quay.io/${{ env.RHQCR_NAMESPACE }}/${{ env.image_name }}
          tags: |
            type=sha,prefix=commit-,format=long
          flavor: |
           latest=true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Buildkit Stage
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.context }}
          file: ${{ env.context }}/${{ env.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          labels: ${{ steps.meta.outputs.labels }}
