name: "docker/ubuntu-lts-base"

env:
  # Ubuntu LTS release name to use for downloading cloud images
  # from Canonical's Partner Images server, among other things.
  UBUNTU_LTS_CODENAME: focal

  # Registry namespaces, to avoid only-lowercase-supported errors
  GHCR_NAMESPACE: ajhalili2006
  RHQCR_NAMESPACE: ajhalili2006

  # Service account stuff for Quay.io
  RHQCR_BOT_ACCOUNT: ajhalili2006+gildedguy
  RHQCR_BOT_PASSWORD: ${{ secrets.RHQCR_SERVICE_ACCOUNT_API_KEY }}

  # GHCR
  GHCR_PAT: ${{ secrets.LTT_STORE_DOT_COM }}
  # may not work if forked in an org, use an bot account instead
  GHCR_USERNAME: ${{ github.repository_owner }}

  # Other stuff for Docker builds
  image_name: ubuntu-base
  context: src/ubuntu-lts-base

  RELEASES_GPG_KEY: ${{ secrets.CURSED_CONTENT_OVER_HERE }}
  RELEASES_GPG_PASSPHARSE: ${{ secrets.COOL_AND_NORMAL }}

on:
  push:
    branches: [ main ]
    paths:
      - "src/ubuntu-lts-base/Dockerfile"
      - "src/ubuntu-lts-base/sources.list.d/*.list"
      - ".trigger-build"
  #schedule:
  #  - cron: "30 3 */11 * *"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './${{env.context}}/overlay/usr/local/bin'
      - name: Lint Dockerfile
        if: ${{ always() }}
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: "./${{env.context}}/Dockerfile"
  build:
     runs-on: ubuntu-latest
     needs: [ lint ]
     steps:
      - uses: actions/checkout@v2
      - name: Login with GHCR
        uses: docker/login-action@v1
        with:
          username: ${{ env.GHCR_USERNAME }}
          password: ${{ env.GHCR_PAT }}
          registry: ghcr.io
      - name: Login with RHQCR
        uses: docker/login-action@v1
        with:
          username: ${{ env.RHQCR_BOT_ACCOUNT }}
          password: ${{ env.RHQCR_BOT_PASSWORD }}
          registry: quay.io
      - name: Generate matadata
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            ghcr.io/${{ env.GHCR_NAMESPACE }}/${{ env.image_name }}
            quay.io/${{ env.RHQCR_NAMESPACE }}/${{ env.image_name }}
          tags: |
            ${{ env.UBUNTU_LTS_CODENAME }}
          flavor: |
           latest=true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build da image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.context }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            RELEASE=${{ env.UBUNTU_LTS_CODENAME }}
